# 2021 

## Mihin tarkoitukseen käytetään rokuronia? Miten kumoat sen vaikutuksen? Millä yksiköllä lihasrelaksaatiota monitoroidaan?

Lihasrelaksaatioon, sugammadeksiinillä (Bridion), TOF% (tavoite 0 luku, 90 TOF%)

## Mihin tarkoitukseen käytetään sevofluraania? Miten seuraat ya syvyyttä?

Yleisanestesian ylläpitokaasuna. MAC (=minimum alveolar concentration, 50% potilaista ei reagoi fluraaniin), Entropia, EEG

## Mihin tarkoitukseen käytetään ondansetronia? Mikä altistaa post-op pahoinvoinnille ja oksentelulle?

Pahoinvoinnin hoitoon ja ehkäisyyn. Naissukupuoli, aikaisempi pahoinvointi post op, opioidien tarve post op, nuori ikä, tupakoimattomuus, myös tietyt leikkaustyypit kuten KNK leikkaukset

## Millä luokalla kuvataan monielinvauriota?

SOFA: hengitys (PaO2/FiO2), verenkierto (hypotensio, MAP <70?), munuaiset (krea), hermosto (GCS), maksa (bil), koagulaatio (trom)

## Potilaalla insuliinihoitoinen diabetes ja verenpainetauti. Mikä on ASA-luokka?

ASA 2 jos diabetes on hyvässä hoitotasapainossa

## Potilas ei avaa silmiään kivulle, ei ääntele, ei liikevastetta kivulle, paljonko GCS?

GCS 3-15p:

Silmien avaaminen 1-4p (spontaanisti, puheelle, kivulle, ei avaa silmiä kivulle)

Puhevaste 1-5p (orientoitunut, sekava, irrallisia sanoja, ääntelyä, ei ääntele)

Liikevaste 1-6p (noudattaa kehotuksia, paikallistaa kivun, väistää kipua, fleksio kivulle, ekstensio kivulle, ei vastetta)

Potilaan GCS on 3p

## Potilas elvytetty VF:stä, saatu elpymään 6 deffauksen jälkeen, paljonko elvytyslääkkeitä on kulunut?

Adrenaliini 2 mg, amiodaroni 450 mg

## Kun potilaalle on saatu laitettua elvytyksessä larynxmaski, mikä on puhallusten ja painallusten suhde?

30:2, mutta ei taukoja koska hengitystiet varmistettu

## Mitä nestettä ei käytetä korvaukseen?

Glukoosipitoisia ylläpitonesteitä (korvaukseen yleensä balansoidut kristalloidit)

## Paljonko on 70kg:sen perusnestetarve päivässä?

2100ml, 25–30ml/kg/vrk

## Potilas tulee akuutin eteisvärinän takia ensiapuun, syönyt viimeksi klo 17, milloin voidaan suorittaa rytminsiirto?

Ennen kardioversiota on oltava 4-6h syömättä, eli klo 21-23 välillä

## Mitä parametreja seuraamalla voidaan seurata yleisanestesian syvyyttä?

Mikä ei lisää riskiä leikkauksen jälkeiseen pahoinvointiin? nais-sp, tupakointi, opioidien postop. käyttö vai aiempien anestesioiden jälkeen koettu pahoinvointi

## Paljonko on ekstrasellulaaritilan volyymi?

20% kehonpainosta, esim. 70kg painoisella 14kg -> 14 litraa

Intrasellulaaritila taas 40% (noin 28 litraa)

## Mikä on anafylaktisen reaktion ensihoito ja millä annoksella?

Ensisijainen lääke on adrenaliini 0.1-1mg i.v. vaikeusasteesta riippuen tai 0.3-0.5mg i.m.

## Potilaalle tehty sappirakonpoistoleikkaus, potilaalla kotilääkkeinä sydänlääkkei, varfariini… Mitä kipulääkkeitä postop. määräät? (vaihtoehtoina a. parasetamoli, b. parasetamoli, nsaid, opioidi.. c… d.parasetamoli + oksynorm)

Paracetamoli + oxynorm (Ei ehkä nsaid koska varfariini)

## Potilaalle tehty lannepisto, jonka jälkeen päänsärkyä, mikä on kyseessä?

Postspinaalipäänsärky, likvoria valuu pistoreiästä ja paineolosuhteet muuttuvat

## Mikä seuraavista ei altista neuropaattiselle kivulle? (ms-tauti, selkärangansairaus, diabetes, menieren tauti, avh)

Menieren tauti (MS, selkärankasairaus, DM, AVH altistavat)

## Opioidien sivuvaikutukset

Sivuvaikutukset ovat annosriippuvaisia. Yleisimpiä ovat ummetus, pahoinvointi, oksentelu, ruokahaluttomuus, hengenahdistus, suun kuivuminen, mioosi, sekavuus, hikoilu, kutina.

## Opioidien metaboloitumis cyp-entsyymi kysymys

CYP2D6

## PEEP tarkoittaa?

Positive-end expiratory pressure eli alveolipaine uloshengityksen loppuvaiheessa

## Distributiivisen shokin aiheuttamat muutokset

Verenkierton jakautunut poikkeavasti eikä sen autoregulaatio toimi välttämättä, arterioleissa vasodilataatiota. Verivolyymi saattaa alussa olla normaali, mutta vasodilaatio ja suonten permeabiliteetin lisääntyminen kehittää hypovoleemisen sokin taudinkuvan.

Taustalla voi olla sepsis, trauma, tai muu voimakkaan inflammatorisen vasteen aiheuttava tila

## Sepsiksen ensihoito

Nestehoito esim. ringer i.v., esim. 500ml boluksina vastetta seuraten, tarv. noradrenaliinia jos verenpainetta ei saada nousemaan

2x veriviljely ja sen jälkeen aloitetaan empiirinen antibiootti, esim. kefuroksiimi 1,5g i.v

## Leikkaukseen / potilaaseen liittyvät riskitekijät

Leikkauksen riskitekijät: kirurgian tai anestesiologian komplikaatiot, esim. infektio, verenvuoto, tromboosi (kir) tai hemodynamiikan romahtaminen, allergia, pahoinvointi, aspiraatio (ane)

Potilaan riskitekijät: raskaus, tupakka, alkoholismi, AK-hoito, korkea BMI, stabiili systeemisairaus kuten hyvän hoitotasapainon DM, vaikea systeemisairaus kuten äskettäinen sydäninfarkti

## Mitä leikkauksen esilääkitykseen voi kuulua?

Kipulääke (paracetamol, NSAID), pahoinvointilääke (ondansetron, betametasoni), antibioottiprofylaksia (metronidatsoli esim), kortikosteroidi tarpeen mukaan (betametasoni, pahoinvoinnin estoon myös)

## Mikä altistaa post-op pahoinvoinnille ja oksentelulle?

Naissukupuoli, aikaisempi pahoinvointi post op, opioidien tarve post op, nuori ikä, tupakoimattomuus, myös tietyt leikkaustyypit kuten KNK leikkaukset

## Miten leikkauspotilaan/akuutisti sairaan potilaan pahoinvointia tulisi hoitaa?

Ehkäisy parasta hoitoa: säännölliseksi listalle lääke jo etukäteen, nestetasapaino, suolentoiminta ja kipu kuntoon myös

Ondansetroni ja DHBP (droperidoli, ei parkinsonpotilaile) parhaita, muista QT-aikaa pidentävä vaikutus setroneilla (hidastaa myös paksusuolen vetoa)

Betametasoni esim tarvittaessa boostaamaan pahoinvoinnin estoa

EI METOKLOPRAMIDIA, HUONO TEHO JA EKSTRAPYRAMIDAALI SIVUVAIKUTUKSET! EI PARKINSONPOTILAILLE ETENKÄÄN!

## Mitä haasteita pulssioksimetrissä on?

Potilaan jäähtyessä (huono perifeerinen perfuusio) epäluotettavat tulokset

Alle 80% saturaatiolla arvot epäluotettavia

Methemoglobiini- ja häkämyrkytyksessä valheellisen korkeita tuloksia

## Puudutuksen/nukutukuksen hyödyt ja haitat?

Nukutus: konehengitys altistaa atelektaaseille, tarvitaan enemmän kipulääkkeitä (heräämöön), parempi ko-operoimattomille potilaille, kognitio voi heikentyä

Puudutus: parempi kivunlievitys jopa heräämöön asti, ei vaikuta kognitioon, AK-hoito vasta-aihe

## Yleisanestesia vs sedaatio?

Sedaation aikana aspiraatioriski koska hengitysteitä ei yleensä varmisteta

Yleisanestesiassa enemmän hemodynaamisia ongelmia (isommat annokset lääkkeitä)

## Mitä analgeetteja yleisanestesiassa voidaan käyttää?

Fentanyyli/opioidit, parasetamoli, NSAID, ketamiini. Puudutuksista apua myös.

## Mitä yleisanesteetteja käytetään?

Propofoli, sevofluraani (desfluraani) -> induktio propofolilla, ylläpito sevofluraanilla

Propofolin ongelmana hypotensio sekä opioidin kanssa hengityslamariski

## Inhalaatioanesteetin edut/haitat?

Helppo annostella, ei tarvetta vastalääkkeelle, ei allergioita, halpa

Pahoinvointia yleisemmin, malignin hypertermian riski, epämiellyttävä haju

## Spinaalipuudutuksen haitat ja riskit?

Postspinaalipäänsärky (likvoria valuu pistoreiästä ja paineolosuhteet muuttuu) hoitona NSAID, lepo, nesteytys

Selkäsärky, jalkasärky, hermovauriot, esim tuntopuutos (parestesia pistäessä ennustaa)

Riskit: epiduraalihematooma, epiduraaliabskessi ”totaalispinaali” jossa hengitys lamautuu, kouristuksia ja tajuttomuutta

## Selitä nosiseptiivinen kipu, neuropaattinen kipu, viskeraalinen kipu?

Kudosvauriokipu (kipureseptorin ärsytys), kipua välittävän hermon vauriokipu, sisäelinkipu (usein vaikea paikantaa)

## Mitä tarkoittaa multimodaalinen analgesia?

Kombinoimalla useita kipulääkkeitä saadaan parempi teho, pidempi vaikutus, pienemmät haitat

Esim. parasetamoli + NSAID + opioidi + puudutus tms.

## Defibrilloitavat ja ei-defibrilloitavat rytmit?

VF ja VT, ei-deffattavat taas sykkeetön rytmi ja asystole

## Milloin elvytystä ei tule aloittaa? Milloin elvytys lopetetaan?

Sekundaariset kuoleman merkit havaittavissa, löydetty asystolesta, ilmeinen kuolemaan johtava vamma, DNR-päätös

Lopetetaan, kun elvytysaika deffattavissa 40min (VF/VT) ja ei-deffattavissa 20min (PEA/ASY)

## Mikä on 4H ja 4T?

Hypoksia, hypotermia, hypovolemia, hypokalemia

Tamponaatio, tromboosi, tensiopneumothorax, toksiinit

## Mitä kuuluu elvytyksen jälkeiseen hoitoon?

SpO2 94-98%, normaali ventilaatiotiheys

RRsyst >100mmHg, tarv. nestehoito kristalloideilla (vasopressiini/noradrenaliini?)

Sedaatio opioideilla/bentsodiatsepiineilla

Lämpötila 32-36C

Sydäninfarktin reperfuusiohoidon tarpeen arviointi

Hyperglykemian esto

## Mitä tarkoitetaan leikkausriskillä ja leikkaus- ja anestesiakelpoisuudella?

Leikkausriski = epäedullinen lopputulos, leikkausta ei voi tehdä tai leikkaus aiheuttaa haittaa potilaalle komplikaation tai virheen myötä

## Kerro anestesiakomplikaatioista?

Huuli-, limakalvo- ja hammasvauriot, hemodynamiikan romahtaminen (ya, puudutus), hermovaurio, hematooma pistospaikassa/epiduraalissa, paikallinen kudosvaurio ekstravasaation (lääkeaine suonen ulkopuoliseen tilaan) takia, aspiraatio, allergia, pahoinvointi

Virtsaretentio sentraalisen puudutuksen jälkeen, postpunktiopäänsärky, pneumothorax, maligni hypertermia, totaalispinaali…

## Mistä seikoista anestesiologi on erityisen kiinnostunut potilaassa?

Allergiat, onko suvussa anestesiaan vaikuttavia ominaisuuksia, aiempien anestesioiden sujuminen (nausea, pelko, vaikea hengitystie), ylipaino, tupakka, päihteet, kognitio…

## Selitä mikä on ASA-luokka?

I = terve potilas

II = lievä sairaus, joka ei vaikuta suorituskykyyn, tupakka, raskaus, BMI 30-40, stabiili DM…

III = merkittävä sairaus, COPD, BMI>40, alkoholismi, hepatiitti, >3kk sitten TIA/sydäninfarkti..

IV = henkeä uhkaava sairaus, <3kk TIA/sydäninfarkti, merkittävä läppävika, sepsis, mun. vt.

V = potilas menehtyy ilman leikkausta, rupturoitunut aneurysma aortassa, aivoverenvuoto, MOF

VI = kuollut elintenluovuttaja

## Miten hyytymisenestolääkitys vaikuttaa anestesiaan? Miten suhtaudut tauottamiseen?

Tauotuksessa konsultoi aina muita lääkäreitä (kardio, neuro jne), aina on tiedettävä miksi AK-hoito käytössä ja saako sitä tauottaa! (Esim. klopidogreeli STEMI jälkeen, EI SAA, stentti trombiriski!) Tiedettävä myös tarviteeko siltahoitoa esim. LMWH.

AK hoito ei estä nukuttamista, mutta estävät epdiuraali- ja spinaalipuudutuksen. Lisääntynyt vuotovaara.

Jos tauotus on riskialtista, ei tauoteta anestesian mahdollistamiseksi, ellei ko. anestesiamuodon valinnalle ole painavia perusteita (esim. vaikea keuhkosairaus -> spinaali parempi kuin ya)

## Mikä on akuuttihoidon ABCDE?

A = airway – turvaa hengitystie

B = breathing – onko hengitys riittävää?

C = circulation – onko verenkierto riittävää?

D = neurological disability – tajunnan taso, puutosoireet, kallonsisäinen paine?

E = expose – tutki potilas järjestelmällisesti, hoida kipua, suojaa kylmältä

## Mitä ovat tukkeutuneen hengitystien tuntomerkkejä? (A = airway)

Vaikeus/kykenemättömyys puhua, poikkeavat hengitysäänet (stridor, kuorsaus, ei hengitysääniä), poikkeavat hengitysliikkeet (apuhengityslihakset, paradoksaalinen rintakehän liike), alentunut tajunnantaso, hypoksia, syanoosi, elottomuus

## Miten huolehdit hengityksen riittävyydestä? (B = breathing)

Hengitys = happeutuminen + ventilaatio

Ongelma voi olla hapetushäiriö (SpO2 tai PaO2 matala) -> lisähappea (muista: keuhkosairailla älä ylihapeta, 88-92% saturaatio riittää)

Lisähapen haitat: altistaa atelektaaseille, happiradikaalien toksisille vaikutuksille

Ja/tai ventilaatiovajaus (CO2 retentio, resp. asidoosi, eli kokrea EtCO2 tai PaCO2)

## Miten turvaat verenkierron? (C = circulation)

Jos shokki -> työdg, onko hypovoleeminen, distributiivinen, kardiogeeninen, obstruktiivinen?

Kompensoitu (takykardia, viileä periferia, janon tunne), vai kompensoimaton (alentunut tajunnan taso, hypotensio, sentraalinen syanoosi, hengitys-ekshaustio)?

Tyrehdytä vuoto, lisähappea, nestehoitoa (esim. ringer/plasmalyte 500ml boluksina vastetta seuraten, EI GLUKOOSIPITOISIA YLLÄPITONESTEITÄ HYPOVOLEMIAAN), potilas trendelenburgin asentoon (ei jos kallovamma, hengitysvaikeus, pään/kaulan vuoto), tarv. vasopressiiniä/noradrenaliinia tms.

## Neurologian tutkiminen? (D = neurological disability)

GCS, pupillat (koko, puoliero, valoreaktiot, katsedeviaatio), Babinski, motoriset puolierot ja mimiikka (liikkuuko raajat, puristusvoima, raajan kannatus, irvistys), puheen sujuvuus, niskajäykkyys

## Miksi nestehoito on tärkeää palovammapotilaalla, mikä on Parklandin kaava, millä nesteytät?

Riittämätön nesteresuskitaatio voi johtaa palovamman syvenemiseen, pidentää shokin kestoa ja kuolleisuutta. Nesteytys myös parantaa kudos- ja elinperfuusiota.

Parklandin kaava: 4ml / kg x palovamma % (puolet 8h aikana, puolet 16h aikana = 24h) ja tarvittaessa nesteytä runsaammin jos tulos ei tyydytä (diureesi 0,5-1ml/kg/h, ei takykardiaa, RR>100mmHg, asidoosi väistyy ja laktaatti laskee). Nesteytys balansoiduilla kristalloideilla

## Kerro palovammashokin patofysiologiasta.

Sekoitus distributiivista, hypovoleemista ja kardiogeenistä shokkia. Nestettä vuotaa ja haihtuu vamma-alueelta, vaurioituneista soluista vapautuu tulehduksen välittäjäaineita ja syntyy laaja inflammatorinen vaste -> verisuonten permeabiliteetti lisääntyy -> turvotus, hypovolemia, perif. resistenssin kasvu, cardiac output pienenee ja shokki syvenee

### Mitä ensivaiheen väistyttyä tapahtuu?

48-72h kohdalla vuotavan alueen solukalvot alkavat eheytyä, sytokiinimyrsky laantuu ja neste pysyy suonissa -> hypervolemiariski jos jatkaa liian korkealla nesteytyksellä!

## astrupin tulkintaa

## kanyylien värit

## opioidit kroonisen neuropaattisen kivun hoidossa

## sepsiksen suolisto-oireet

## kakektisen, monisairaan todella kivuliaan potilaan kipulääkkeen annostelu päivystyksessä

## tipan valinta viikon kestävässä antibioottihoidossa

## perustäyttöneste leikkauksessa

## hypokalemian hoito

## mitkä tekijät voivat estää leikkauksen?

## elvytetyn potilaan uloshengityksen CO2 pitoisuus ROSCin jälkeen?

## NEWS pisteytyksen käyttö

## Mikä on inotrooppi?

## mikä aiheuttaa AKI:n seuraavista (oikea vastaus dehydraatio ja NSAID)

## potilastapaus: potilaan rinnuksilla on oksennusta, ht 8 krt/min, saturoi huonosti, mitä teet hengityksen turvaamiseksi?

## vitamiinilisät parenteraalisessa ravitsemuksessa

## mitkä seuraavista on heikkoja opioideja? a) tramadoli ja kodeiini b) hydromorfoni ja kodeiini c) rokuroni ja tramadoli d) fentanyyli ja kodeiini

## missä asennossa elvytetty tai aivovamman saanut pitää kuljettaa? a) vaakatasossa b) trendelenburgissa c) pää hieman koholla

## SIRS-kriteerit

## Anafylaktisen sokin tyyppi? 1. distributiivinen, 2. kardiogeeninen, 3.hypovoleeminen ja joku neljäs vaihtoehto

## Hyponatremiasta monta kysymystä

## Potilas hengittää spontaanisti, saturaatio 96%, GCS 5, mitä teet hengitysteille? (vaihtoehtoina intubointi, seuranta, nielutuubi, maskiventilaatio)

## Mikä on ei ole vasta-aihe puudutukselle (spinaali/epiduraali)? 1. potilas on lapsi, 2. puudutusalueen infektio, 3. korjaamaton hypovolemia, 4. joku

## Mikä ei ole vasta-aihe tulehduskipulääkkeelle? hyytymisenestolääkitys, sairastettu sydäninfarkti, reumalääkitys ja joku vielä

## Potilaan PaCO2 8.9, mitä teet? ventiloin lisää/vähemmän/annetaan korjaantua itsestään

## Kuka päättää anestesiamuodon? potilas/kirurgi/ane/loppupeleissä anestesialääkäri leikkauksen vaatimusten ja potilaan toiveiden mukaan

## Covid-potilas vaipumassa tajuttomaksi, HT 4/min, oksennellut, mitä teet? -> intubaatio

## Turvallinen vieläkin käytössä oleva kolloidi? vaihtoehtoina albumiini, mannitoli, kaksi muuta

## Mitä tarkoittaa allodynia?

