# 2023

Taas vaihtoehdot puuttuvat suurimmasta osasta ja kysymyksenasettelua ei aina saatavilla. Näiden suhteen taas olen koittanut kirjoittaa tärkeimmät pointit. 

## Verenpainetavoite elvytyksen jälkeen 

- >100 map: 50

## Opioidien farmakologia

Elvytyksessä monitorilla näkyy sinusrytmi, mitä teet

## Amiodaroni 

- = rytmihäiriölääke

## Alkoholistille pitää antaa: tiamiini, joku, glukagoni, joku

## Mikä sokki kun sydäntamponaatio

## Mikä puudute lonkkaleikkauspotilaalle käypä hoidon mukaan

## Elvytyksen jälkeen potilas kakoo intubaatioputkea, mitä teet

## Elektiivinen leikkaus tarkoittaa

## NIV

## Astrup tulkinta

## Puuduteainemyrkytyksen ensioireet

## Mikä neste kun joku aivoturvotusjuttu?

## Mikä tärkeintä hoitotilanteen johtajana? 

- Johtaminen 😀

## Milloin ROSC saavutettu? 

- verta kierrättävä rytmi

## Mikä on tärkeintä elvytyksessä? 

- varhainen deffaus ja laadukas ppe

## Mitkä seuraavista ovat anesteetteja? -vaihtoehtoina opioideja, propofoli ym., rokuroni

## Mikä ei ole anafylaksian oire? -metallin maku suussa

## Kompensoitu vai kompensoitumaton respiratorinen/metabolinen asidoosi/alkaloosi

## Elvytystilanne: 2 elvyttäjää, voiko suoniyhteyden avata vai keskitytäänkö laadukkaaseen painelu-puhalluselvytykseen?

## Mikä seuraavista on keskivahva opioidi? 

- Buprenorfiini

## GCS pisteiden laskeminen potilastapauksesta

< 7 


## Aivotapahtuma/sydäntapahtuma, milloin aikaisintaan elektiivinen leikkaus?

## Sepsis, mikä ensisijainen vasoaktiivi? 

- noradrenaliini

## Mistä laktaatin nousu johtuu?

## Elvytyksen aikana minimimonitorointi

## Post-op. pahoinvoinnille altistavat tekijät 

- tupakointi ei altista

## Anafylaksian hoito 

- adrenaliini

## Pulssioksimetrin virhelähteet

## ISBAR, mitä S-kirjain tarkoittaa

## CYP2D6-entsyymin aktiivisuuden vaikutus kodeiinin analgeettiseen vaikutukseen

## Mitä monitoroidaan rutiinisti heräämössä?

## Vanhuksen kivun hoito

## Raskaana olevan anestesia

## Mikä näistä liittyy akuutista kudosvauriosta johtuvaan kipuun 

- nosiseptio

## Mikä näistä ei ole opioidien sivuvaikutus

- ummetus
- euforia
- hengityslama
- joku neljäs